-- Canonical replay v3 is append-only. Keep immutable record batches outside the replay envelope so
-- a five-second checkpoint inserts only the new suffix instead of re-gzipping and re-TOASTing the
-- entire game-so-far. The parent counter makes completeness cheap to validate on every read.
ALTER TABLE game_replays
    ADD COLUMN canonical_record_count INT NOT NULL DEFAULT 0;

CREATE TABLE game_replay_chunks (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    replay_id    BIGINT NOT NULL REFERENCES game_replays (id) ON DELETE CASCADE,
    first_record INT    NOT NULL,
    record_count INT    NOT NULL CHECK (record_count > 0),
    data         TEXT   NOT NULL,
    UNIQUE (replay_id, first_record)
);

CREATE INDEX idx_game_replay_chunks_replay_order
    ON game_replay_chunks (replay_id, first_record);
